apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: ${project_name}
spec:
  type: generic
  secretRef:
    name: webhook-receiver-token
  resources:
    - apiVersion: image.toolkit.fluxcd.io/v1beta1
      kind: ImageRepository
      name: ${project_name}
    - apiVersion: image.toolkit.fluxcd.io/v1beta2
      kind: ImageUpdateAutomation
      name: ${service_name}