apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: http-broadcaster
spec:
  chart:
    spec:
      chart: myChart
      reconcileStrategy: ChartVersion
      version: "2.x.x"
      sourceRef:
        kind: HelmRepository
        name: myChart
        namespace: infrastructure
  interval: 10m0s
  values:
    environment: "prd"
    app:
      image:
        tag: 2.1.5 # {"$imagepolicy": "system:http-broadcaster:tag"}
    autoscaling:
      enabled: false
    vault:
      path: "app/data/http-broadcaster/prd/envVars"
    ingress:
      autoIngress:
        host: "purgatory.example.com"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
