---

- name: User deployment related tasks
  ansible.builtin.include_tasks: users.yml
  tags: all,users,rootonly

- name: Firewall deployment related tasks
  ansible.builtin.include_tasks: firewall.yml
  tags: all,firewall

- name: Ssh deployment related tasks
  ansible.builtin.include_tasks: ssh.yml
  tags: all,ssh
