apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: helm-registry-gitlab
spec:
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: helm-registry-gitlab
    deletionPolicy: Retain
  dataFrom:
  - extract:
      key: kubernetes-secrets/helm-registry-gitlab
