---

- name: Systemd daemon_reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart mongodb
  ansible.builtin.systemd_service:
    name: mongod
    state: restarted

- name: Restart pbm-agent
  ansible.builtin.systemd_service:
    name: pbm-agent
    state: restarted
