apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: gatekeeper
spec:
  namespaceSelector:
    matchNames:
      - gatekeeper
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - gatekeeper
  podMetricsEndpoints:
    - port: metrics
