apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: inf-traefik-core
  namespace: infrastructure
spec:
  interval: 5m
  path: ./infrastructure/staging/fundamental-apps/traefik/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: inf-traefik-resources
  namespace: infrastructure
spec:
  dependsOn:
    - name: inf-traefik-core
  interval: 5m
  path: ./infrastructure/staging/fundamental-apps/traefik/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
