apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: inf-gatekeeper-core
  namespace: gatekeeper
spec:
  interval: 5m
  path: ./infrastructure/base/gatekeeper/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: inf-gatekeeper-resources
  namespace: gatekeeper
spec:
  dependsOn:
    - name: inf-gatekeeper-core
  interval: 5m
  path: ./infrastructure/base/gatekeeper/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
