---

- name: Daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart unbound exporter
  ansible.builtin.systemd_service:
    name: unbound_exporter
    state: restarted

- name: Reload Unbound
  ansible.builtin.systemd_service:
    name: unbound
    state: reloaded
