apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: http-broadcaster
  labels:
    team: system
spec:
  imageRepositoryRef:
    name: http-broadcaster
  filterTags:
    pattern: '^v?(?P<rv>[0-9]+\.[0-9]+\.[0-9]+)$'
    extract: '$rv'
  policy:
    semver:
      range: '^2.x.x-0'
