---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure
resources:
    - vault-secret-store.yaml
    - vault-secret-store-app.yaml
    - registry-credentials.yaml
    - longhorn-s3-backup-secret.yaml
