apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: longhorn-s3-backup-secret
spec:
  externalSecretName: "longhorn-s3-backup-secret"
  refreshTime: "1h"
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - infrastructure
  externalSecretSpec:
    secretStoreRef:
      name: vault-secret-store
      kind: ClusterSecretStore
    refreshInterval: "72h"
    target:
      name: longhorn-s3-backup-secret
      deletionPolicy: Retain
    dataFrom:
      - extract:
          key: kubernetes-secrets/longhorn/s3-backup-secret
