apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store
spec:
  provider:
    vault:
      server: "https://vault.example.com"
      path: "kubernetes-secrets"
      version: "v2"
      auth:
        appRole:
          path: "approle"
          roleId: ""
          secretRef:
            name: "vault-k8s-external-secrets"
            namespace: infrastructure
            key: "secret-id"
