apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: http-broadcaster
spec:
  chart:
    spec:
      chart: myChart
      reconcileStrategy: ChartVersion
      version: "2.x.x"
      sourceRef:
        kind: HelmRepository
        name: myChart
        namespace: infrastructure
  interval: 10m0s
  values:
    environment: "stg"
    app:
      image:
        tag: 2.2.0-rc.1 # {"$imagepolicy": "system:http-broadcaster:tag"}
    autoscaling:
      enabled: false
    vault:
      path: "app/data/http-broadcaster/stg/envVars"
    # Test to verify that Traefik is not rejecting requests for being
    # outside limit size.
    ingress:
      middlewares:
        buffering:
          enabled: false
      autoIngress:
        host: "purgatory.stg.example.com"
    # Telling the chart that we want the service to be scrape.
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
