---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: http-broadcaster
spec:
  chart:
    spec:
      chart: myChart
      reconcileStrategy: ChartVersion
      version: "2.x.x"
      sourceRef:
        kind: HelmRepository
        name: myChart
        namespace: infrastructure
  interval: 10m0s
  values:
    environment:
    fullnameOverride: "http-broadcaster"

    app:
      name: "app"

      image:
        repository: gitlabregistry.example.com/infrastructure/http-broadcaster
        pullPolicy: IfNotPresent
        tag:

      labels:
        technology: "go"
        role: "api"

      resources:
        requests:
          memory: 64Mi
          cpu: 200m
        limits:
          memory: 64Mi
          cpu: 400m

      containerPort:
        broadcaster: 6081

      readinessProbe:
        exec:
          command:
            - curl
            - -f
            - -L
            - -m
            - "5"
            - "127.0.0.1:6081/healthcheck"

      livenessProbe:
        exec:
          command:
            - curl
            - -f
            - -L
            - -m
            - "5"
            - "127.0.0.1:6081/healthcheck"

      command:
        - "/bin/sh"
        - "-c"
        - "[ -f /vault/secrets/.env ] && http-broadcaster --metrics"

      lifecycle: {}

      securityContext:
        capabilities:
          drop:
            - ALL
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault

    # Generic sidecars
    nginx:
      enabled: false

    fpmExporter:
      enabled: false

    elasticAgent:
      enabled: false

    logrotate:
      enabled: false

    imagePullSecrets:
      - name: registry-credentials

    vault:
      enabled: true

    serviceAccount:
      create: true

    service:
      extraPorts:
        - name: web
          port: 6081
          targetPort: 6081

    ingress:
      enabled: true
      autoIngress:
        enabled: true
        path: "/"
        port: 6081

    replicaCount: 2

    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 1
      targetCPUUtilizationPercentage: 40
