apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure
resources:
  - middleware-traefik-dashboard-basic-auth.yaml
  - secret-traefik-dashboard-basic-auth.yaml
  - ingress-route-public-dashboard-prd.yaml
