---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      version: "0.14.x"
      sourceRef:
        kind: HelmRepository
        name: external-secrets-operator
        namespace: infrastructure
  interval: 10m0s
  values:
    replicaCount: 3
    affinity: {}

    installCRDs: true

    crds:
      createClusterExternalSecret: true
      createClusterSecretStore: true
      createPushSecret: true

    leaderElect: true
    concurrent: 3

    serviceAccount:
      create: true
      automount: true

    rbac:
      create: true

    resources:
      requests:
        cpu: 10m
        memory: 32Mi

    serviceMonitor:
      enabled: false
      interval: 30s
      scrapeTimeout: 25s

    metrics:
      service:
        enabled: false

    podDisruptionBudget:
      enabled: true
      minAvailable: 1
      # maxUnavailable: 1

    webhook:
      create: true
      replicaCount: 1
      rbac:
        create: true
      serviceAccount:
        create: true
        automount: true

      podDisruptionBudget:
        enabled: true
        minAvailable: 1
        # maxUnavailable: 1

      serviceMonitor:
        enabled: false
        interval: 30s
        scrapeTimeout: 25s

      metrics:
        service:
          enabled: false

      resources:
        requests:
          cpu: 10m
          memory: 32Mi

      affinity: {}

    certController:
      create: true
      requeueInterval: "5m"
      replicaCount: 1

      rbac:
        create: true
      serviceAccount:
        create: true
        automount: true

      podDisruptionBudget:
        enabled: true
        minAvailable: 1
        # maxUnavailable: 1

      serviceMonitor:
        enabled: false
        interval: 30s
        scrapeTimeout: 25s

      metrics:
        service:
          enabled: false

      resources:
        requests:
          cpu: 10m
          memory: 32Mi

      affinity: {}
