apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure
resources:
  - flux-podmonitor.yaml
  - php-fpm-exporters-servicemonitor.yaml
  - rabbitmq-servicemonitor.yaml
  - python-metrics-servicemonitor.yaml
  - php-metrics-servicemonitor.yaml
  - http-broadcaster-servicemonitor.yaml
