apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/longhorn/
  - recurringjob-backup-longhorn.yaml
  - recurringjob-snapshot-longhorn.yaml
patches:
  - path: hr-longhorn.yaml
