---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: infrastructure
spec:
  cron: "0 19 * * *"
  task: "backup"
  groups:
  - default
  retain: 7
  concurrency: 3
