---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot-hourly
  namespace: infrastructure
spec:
  cron: "0 * * * *"
  task: "snapshot"
  groups:
  - default
  retain: 3
  concurrency: 3
