---

- name: Import install tasks
  ansible.builtin.include_tasks: install.yml
  tags: install

- name: Import backup related tasks
  ansible.builtin.include_tasks: backup.yml
  tags: config,backup

- name: Import monitoring tasks
  ansible.builtin.include_tasks: monitoring.yml
  tags: config,monitoring,pmm_register

- name: Import database related tasks
  ansible.builtin.include_tasks: databases.yml
  tags: databases
