---

rabbitmq_cluster_name: "default"
rabbitmq_admin_username: "admin"
rabbitmq_app_users: ""
rabbitmq_vhosts: ""
rabbitmq_plugins: "rabbitmq_management,rabbitmq_shovel,rabbitmq_prometheus,rabbitmq_shovel_management"
rabbitmq_collect_statistics_interval: 30000
