apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: inf-prometheus-core
  namespace: infrastructure
spec:
  interval: 5m
  path: ./infrastructure/base/prometheus/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: prometheus-operator
      namespace: infrastructure
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: inf-prometheus-resources
  namespace: infrastructure
spec:
  dependsOn:
    - name: inf-prometheus-core
  interval: 5m
  path: ./infrastructure/base/prometheus/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
