---
- name: Reload nftables
  ansible.builtin.systemd:
    name: nftables
    state: reloaded

- name: Reload fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: reloaded

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: Restart ssh
  ansible.builtin.systemd:
    service: sshd
    state: restarted

- name: Restart rsyslog
  ansible.builtin.systemd:
    service: rsyslog
    state: restarted
